import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useSession } from 'next-auth/react'
import Link from 'next/link'

import Layout from '@components/Layout'
import EditablePage from '@components/EditablePage'
import Button from '@ui/Button'

const Home: NextPage = () => {
  const { data: session, status } = useSession()

  if (status === 'authenticated')
    return (
      <>
        <Head>
          <title>DailyThought</title>
          <meta name="description" content="Write your daily thoughts" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <div className="min-h-screen max-w-4xl ml-auto mr-auto">
            <h1 className="text-5xl font-bold mb-5">
              Welcome {session?.user?.name}!
            </h1>
            <h2 className="text-3xl mb-2">{new Date().toLocaleDateString()}</h2>
            <h3 className="text-xl text-gray-600">
              What&apos;s on your mind today?
            </h3>
            <EditablePage />
          </div>
        </Layout>
      </>
    )

  if (status === 'loading')
    return (
      <div className="h-screen grid place-items-center p-10">
        <div className="relative h-28 w-28 animate-spin">
          <Image src="/logo/logo.png" alt="logo" layout="fill" />
        </div>
      </div>
    )
  return (
    <>
      <Head>
        <title>DailyThought</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col items-center justify-center text-center gap-8 my-10">
          <div className="flex gap-5 flex-col items-center max-w-xl">
            <div className="relative w-60 h-60 overflow-hidden rounded-full">
              <Image src="/brain.png" layout="fill" alt="" />
            </div>
            <h1 className="text-4xl sm:text-6xl md:text-7xl font-extrabold">
              We create your daily archive
            </h1>
            <p className="text-normal md:text-lg text-neutral-700">
              Store your thoughts, reflections, speculations, and deliberations
              daily to create a chronic of your mind.
            </p>
            <Link href="/api/auth/signin">
              <a>
                <Button>Sign Up</Button>
              </a>
            </Link>
            {/* <h2 className="text-4xl sm:text-7xl md:text-8xl font-extrabold">
                <span className="bg-clip-text text-transparent bg-gradient-to-b from-pink-500 to-purple-500">
                  Thoughts
                </span>
              </h2>
              <h2 className="text-4xl md:text-8xl font-extrabold">
                <span className="bg-clip-text text-transparent bg-gradient-to-b from-purple-500 to-teal-500">
                  Reflections
                </span>
              </h2>
              <h2 className="text-4xl md:text-8xl font-extrabold">
                <span className="bg-clip-text text-transparent bg-gradient-to-b from-teal-500 to-purple-500">
                  Speculations
                </span>
              </h2>
              <h2 className="text-4xl md:text-8xl font-extrabold">
                <span className="bg-clip-text text-transparent bg-gradient-to-b from-purple-500 to-pink-500">
                  Deliberations
                </span>
              </h2> */}
          </div>
        </div>
      </Layout>
    </>
  )
}

export default Home
